In [1]:
import pandas as pd
import numpy as np

In [14]:
# Load dataset
df = pd.read_csv("The Titanic Dataset.csv")

# Show first 5 rows
df.head()

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90

In [15]:
print("Shape of dataset:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

Shape of dataset: (1302, 10)

Column Names:
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1302 non-null   object
 1   2       1302 non-null   object
 2   3       1302 non-null   object
 3   4       1301 non-null   object
 4   5       1301 non-null   object
 5   6       1045 non-null   object
 6   7       1300 non-null   object
 7   8       1300 non-null   object
 8   9       1296 non-null   object
 9   10      1302 non-null   object
dtypes: object(10)
memory usage: 101.8+ KB

In [17]:
df.describe(include='all')

,1,2,3,4,5,6,7,8,9,10
count,1302,1302,1302,1301,1301,1045,1300,1300,1296,1302
unique,1301,4,3,1297,3,98,10,283,4,1301
top,1,3,0,"Connolly, Miss. Kate",male,24,0,13,S,01-Jan-90
freq,2,700,801,2,835,47,781,59,905,2

In [18]:
missing = df.isnull().sum()

print("Missing Values:\n")
print(missing[missing > 0])

Missing Values:

4      1
5      1
6    257
7      2
8      2
9      6
dtype: int64